config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'tasks', to: 'tasks#index'

  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  get 'tasks/:id/edit', to: 'tasks#edit', as: :tasks_edit
  patch 'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy'

  get 'tasks/:id', to: 'tasks#show', as: :task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.delete
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container mt-5">
  <h1>Edit task</h1>
  <%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
  <% end %>

  <div class="controls">
    <span class="mt-3">
      <i class="fas fa-ban"></i>
      <h6 class="inline"><%= link_to 'Cancel', task_path(@task) %></h6>
    </span>

    <span class="mt-3">
      <i class="fas fa-undo"></i>
      <h6 class="inline"><%= link_to 'Back to list of tasks', tasks_path %></h6>
    </span>
  </div>

</div>

app/views/tasks/index.html.erb
<div class="container mt-5">
  <h1>My tasks</h1>
  <ul class="list-formatted">
    <% @tasks.each do |task| %>
    <li>
      <% if task.completed %>
      <i class="far fa-check-square me-3"></i>
      <% else %>
      <i class="far fa-square me-3"></i>
      <% end %>
      <%= link_to task.title, task_path(task) %>
      <%= link_to task_path(task), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
        <i class="fas fa-trash-alt ms-3"></i>
      <% end %>
    </li>
    <% end %>
  </ul>
  <i class="fas fa-plus-square me-3"></i> <%= link_to 'Add new task', tasks_new_path %>
</div>

app/views/tasks/new.html.erb
<div class="container mt-5">
  <h1>New task</h1>
  <%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
  <% end %>
  <div class="controls">
    <span class="mt-3">
      <i class="fas fa-ban"></i>
      <h6 class="inline"><%= link_to 'Cancel', tasks_path %></h6>
    </span>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container mt-5">
  <h1><%= @task.title %></h1>
  <div class="card p-4 grey-background">
    <p><%= @task.details %></p>
  </div>
  <span>
    <% if @task.completed %>
    <i class="far fa-check-square me-3"></i>
    <% else %>
    <i class="far fa-square me-3"></i>
    <% end %>
    <%= @task.completed ? 'This task is completed' : 'This task has not been completed yet' %>
  </span>

  <div class="controls">
    <span class="mt-3">
      <i class="fas fa-undo"></i>
      <h6 class="inline"><%= link_to 'Back', tasks_path %></h6>
    </span>

    <span class="mt-3">
      <i class="far fa-edit"></i>
      <h6 class="inline"><%= link_to 'Edit', tasks_edit_path %></h6>
    </span>
  </div>
</div>